network:
  device: cuda
  dtype: float32
training:
  name: ViTV8fine_tune2
  iterations: 150
dataset:
  name: ContestHD
  offset: 0
  batch_size: 50
optimizer:
  name: Adam
  params:
    amsgrad: True
defaults:
  - defaults