search_attention: False
network:
  device: cuda
  dtype: float32
training:
  name: AttentionUNetV2_ld
  iterations: 150
dataset:
  name: crlb_test2
  save: crlb
  offset: 0
  batch_size: 50
optimizer:
  name: Adam
  params:
    amsgrad: True
defaults:
  - defaults