network:
  device: cuda
  dtype: float32
training:
  name: ViTV6
  iterations: 150
dataset:
  name: crlb_test
  offset: 0
  batch_size: 250
optimizer:
  name: Lion
  params:
    amsgrad: True
defaults:
  - defaults
