search_attention: False
network:
  device: cuda
  dtype: float32
training:
  name: AttentionUNetV2
  iterations: 150
dataset:
  name: lab_logo_dense2
  offset: 0
  batch_size: 50
optimizer:
  name: Adam
  params:
    amsgrad: True
defaults:
  - defaults