search_attention: False
network:
  device: cuda
  dtype: float32
training:
  name: AttentionUNetV2
  iterations: 150
dataset:
  name: airyscan_approaching_lines
  save: approaching_lines
  offset: 0
  batch_size: 50
optimizer:
  name: Adam
  params:
    amsgrad: True
defaults:
  - defaults