network:
  device: cuda
  dtype: float32
training:
  name: DecodeV2
  iterations: 150
dataset:
  name: lab_logo6
  offset: 0
  batch_size: 250
optimizer:
  name: Lion
  params:
    amsgrad: True
defaults:
  - defaults
