
training:
  #base training file (can also be used for tranfer learning)
  base: DecodeV4
  #todo runs with batch size 50
  #target training file
  name: DecodeV4
  #number of training iterations
  iterations: 150
dataset:
  #list of training datasets
  train: [airyscan_complex2]
  #batch size to train on hardwarelimited
  batch_size: 50
  height: 60
  width: 60
  #size: 5000
  #offset for frames to train on
  offset: 0
  #validation dataset
  validation: airyscan_complex_test2
  #uses log of dataset
defaults:
  - dataset:
  - optimizer: adamw