
training:
  base: ViTVtest
  name: ViTVtest
  iterations: 450
dataset:
  train: [airyscan_ld]
  batch_size: 250
  height: 60
  width: 60
  #size: 5000
  offset: 0
  validation: random_highpower_test
defaults:
  #uses log of dataset
  - defaults